// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yivnximszyzjebpjygrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpdm54aW1zenl6amVicGp5Z3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MDg3MjgsImV4cCI6MjA1Mzk4NDcyOH0.6gJlyoy7zYbQZ4eFZuxbzegCsN8AIN6t6nh-5-tmEdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);